### ISSUE TITLE
Smooth upgrade

### ISSUE THREAD

**Issue by htruong** [opencardev/crankshaft#10]
In the current state of Crankshaft, every upgrade needs to be done by reflashing the SD card. A better way to upgrade would be either OTA or at least through a USB drive/Android phone.

**Comment by htruong** [comment]
Depends on #8.

**Comment by halflifestudios** [comment]
Is there a remote or USB way to update the builds? My device is screwed into the enclosure which makes it difficult to get access to the SD card everytime to upgrade. An easier or remote way would be ideal in order to keep up with your great updates. The software has been working great and have been using it every day. Sometimes my Note 8 doesn't recognize right away and I have to reboot the OS, but other than that it has been doing very well. Thank you again for all your work on this endeavor.

**Comment by hawkeyexp** [comment]
With upcoming builds based on crankshaft-ng branch system will get an option to update system by attach usb stick with update file :-)
