### ISSUE TITLE
[CSNG] About day\night mode

### ISSUE THREAD

**Issue by bttf92** [opencardev/crankshaft#170]
Just some small advise. I have set the night mode time to 7PM. I noticed that when I boot crankshaft past this hour it will always start in day mode and then after a minute it switches to night mode. If rtc is enabled, it's possible that crankshaft will boot with the correct mode according the hour? (EDIT: If Crankshaft already works this way, can this be a problem with my rtc chip?)

And another small thing, If I toggle manually day mode during night time and then not connect the phone within the minute, crankshaft will switch back to night mode. I think will be nice if manually set the day\night mode it will stay regardless of the hour until a reboot.

You are doing a terrific job, keep it up!

**Comment by hawkeyexp** [comment]
It's not really a bug or problem with your rtc.
This is caused by current system design. In background there are running timers which checks if it is day/night. The check interval is 60 seconds.
The manually toggle is primary for users without rtc to switch between day/night.
This behaviour will be optimized later.
